package com.odyssey.swiftnotes.helpers

/**
 * Generated by ObscuriaAndroidDAOGenerator
 */

class Categorie {
    var id: Long = 0
    var titre: String? = null
    var couleur: String? = null

    constructor() {}

    constructor(id: Long, titre: String, couleur: String) {
        this.id = id
        this.titre = titre
        this.couleur = couleur
    }

}